version: '3.1'

services:

  db:
    image: postgres:13.2-alpine
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: likelocation
      POSTGRES_USER: likelocation
      POSTGRES_DB: likelocation