version: '3.1'

services:

  db:
    image: postgres:13.2-alpine
    restart: always
    ports: 
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: likelocation
      POSTGRES_USER: likelocation
      POSTGRES_DB: likelocation

  flyway:
    image: flyway/flyway:7.9.0-alpine
    command: -url=jdbc:postgresql://db:5432/likelocation -user=likelocation -password=likelocation -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on: 
      - db

  app:
    image: backend-likelocation-app
    ports: 
      - 8081:8080
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on: 
      - db
